services:
  postgres:
    image: postgres:16-alpine
    container_name: fashion_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fashionuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Ckdshfh231161}
      POSTGRES_DB: ${POSTGRES_DB:-fashion_platform}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fashionuser}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: .
    # For production, use optimized Dockerfile:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.optimized
    container_name: fashion_backend
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
      "

volumes:
  postgres_data:
    driver: local
